server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bike?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  application:
    name: my-provider-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package: com/wen/pojo



